# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TemplateDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TemplateDemo
  pod 'Alamofire'
  pod 'Moya'
  pod 'PromiseKit'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'RealmSwift'
  pod 'DZNEmptyDataSet'
  pod 'KeychainSwift', '~> 16.0'

  target 'TemplateDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TemplateDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
